model_params:
  fp16: false
  model: Finetune
  model_name: resnet50
  num_classes: 5

args:
  expdir: "src"
  logdir: &logdir "./logs/stage1"
  baselogdir: "./logs/stage1_base"

stages:

  state_params:
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  data_params:
    num_workers: 4
    batch_size: 32

    train_csv: '/raid/bac/kaggle/cassava-disease/notebooks/csv/train_0.csv'
    valid_csv: '/raid/bac/kaggle/cassava-disease/notebooks/csv/valid_0.csv'
    datapath: "/"

  criterion_params:
    criterion: FocalLoss


  # train head
  stage1:

    state_params:
      num_epochs: 5

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.1

    callbacks_params: &callbacks
      loss:
        callback: MixupLossCallback
      optimizer:
        callback: OptimizerCallback
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1]
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 3

  stage2:

    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: Adam
      lr: 0.0001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [4, 8]
      gamma: 0.1

    callbacks_params: *callbacks